[package]
name = "keccak-halo2"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo2 = {path="../halo2"}
sha3 = {version="0.9.1"}
hex-literal = {version="0.3.3"}